_wandb:
    value:
        cli_version: 0.21.0
        e:
            ipyt647g6q3dbx3azle69sqoid0p9uqd:
                args:
                    - --node-ip-address=192.168.10.102
                    - --node-manager-port=36323
                    - --object-store-name=/tmp/ray/session_2025-08-07_23-49-41_053236_4141955/sockets/plasma_store
                    - --raylet-name=/tmp/ray/session_2025-08-07_23-49-41_053236_4141955/sockets/raylet
                    - --redis-address=None
                    - --metrics-agent-port=59576
                    - --logging-rotate-bytes=536870912
                    - --logging-rotate-backup-count=5
                    - --runtime-env-agent-port=65210
                    - --gcs-address=192.168.10.102:64120
                    - --session-name=session_2025-08-07_23-49-41_053236_4141955
                    - --temp-dir=/tmp/ray
                    - --webui=127.0.0.1:8265
                    - --cluster-id=191666f5d00010d619fcb347feec62691393ab745d9cdc9f1881027f
                    - --startup-token=192
                    - --worker-launch-time-ms=1754581784852
                    - --node-id=53914f99c3b6dd4a3189993090fe09cdcf234cd82297e769457a48ba
                    - --runtime-env-hash=-1624044036
                    - --enable-resource-isolation=false
                cpu_count: 96
                cpu_count_logical: 192
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "943412031488"
                        used: "502109990912"
                email: httsangaj@connect.ust.hk
                executable: /home/httsangaj/miniconda3/envs/atlas-rl/bin/python3
                git:
                    commit: ff469b6332a031424188fc79fbf798266a1d3755
                    remote: git@github.com:gzone0111/autograph-r1.git
                gpu: NVIDIA L20
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 11776
                      memoryTotal: "48305799168"
                      name: NVIDIA L20
                      uuid: GPU-bcc6d970-9050-f912-2169-58ecda253b2e
                    - architecture: Ada
                      cudaCores: 11776
                      memoryTotal: "48305799168"
                      name: NVIDIA L20
                      uuid: GPU-1cca740e-8ee6-c009-d053-b57c4e7d8ae8
                    - architecture: Ada
                      cudaCores: 11776
                      memoryTotal: "48305799168"
                      name: NVIDIA L20
                      uuid: GPU-db452531-23dd-a755-4fdd-8938a97482b6
                    - architecture: Ada
                      cudaCores: 11776
                      memoryTotal: "48305799168"
                      name: NVIDIA L20
                      uuid: GPU-54bf7be3-267c-02bf-3dd0-4edb220c17a5
                    - architecture: Ada
                      cudaCores: 11776
                      memoryTotal: "48305799168"
                      name: NVIDIA L20
                      uuid: GPU-6ab64c59-f25c-9ccc-1b25-93228f536cbd
                    - architecture: Ada
                      cudaCores: 11776
                      memoryTotal: "48305799168"
                      name: NVIDIA L20
                      uuid: GPU-c7e9b483-97cd-3538-be61-7ac3814861a2
                    - architecture: Ada
                      cudaCores: 11776
                      memoryTotal: "48305799168"
                      name: NVIDIA L20
                      uuid: GPU-c1687028-9023-b481-d57e-35d48d9cbe19
                    - architecture: Ada
                      cudaCores: 11776
                      memoryTotal: "48305799168"
                      name: NVIDIA L20
                      uuid: GPU-79ebcfde-b083-5ea7-2b71-f46c051c3ea8
                host: songcpu7
                memory:
                    total: "1081972723712"
                os: Linux-6.8.0-65-generic-x86_64-with-glibc2.35
                program: /home/httsangaj/miniconda3/envs/atlas-rl/lib/python3.10/site-packages/ray/_private/workers/default_worker.py
                python: CPython 3.10.18
                root: /home/httsangaj/projects/atlas-rl-dirs/autograph-r1
                startedAt: "2025-08-07T15:51:21.940992Z"
                writerId: ipyt647g6q3dbx3azle69sqoid0p9uqd
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 11
                - 30
                - 41
                - 49
                - 50
                - 51
                - 53
                - 71
                - 98
                - 105
            "2":
                - 1
                - 5
                - 11
                - 30
                - 41
                - 49
                - 50
                - 51
                - 53
                - 71
                - 98
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.18
            "5": 0.21.0
            "6": 4.51.1
            "12": 0.21.0
            "13": linux-x86_64
actor_rollout_ref:
    value:
        actor:
            checkpoint:
                load_contents:
                    - model
                    - optimizer
                    - extra
                save_contents:
                    - model
                    - optimizer
                    - extra
            clip_ratio: 0.2
            clip_ratio_c: 3
            clip_ratio_high: 0.2
            clip_ratio_low: 0.2
            entropy_checkpointing: false
            entropy_coeff: 0
            entropy_from_logits_with_chunking: false
            fsdp_config:
                forward_prefetch: false
                fsdp_size: -1
                offload_policy: false
                optimizer_offload: false
                param_offload: false
                reshard_after_forward: true
                wrap_policy:
                    min_num_params: 0
            grad_clip: 1
            kl_loss_coef: 0.001
            kl_loss_type: low_var_kl
            loss_agg_mode: token-mean
            optim:
                lr: 1e-06
                lr_warmup_steps: -1
                lr_warmup_steps_ratio: 0.285
                min_lr_ratio: 0
                num_cycles: 0.5
                total_training_steps: 500
                warmup_style: constant
                weight_decay: 0.01
            policy_loss:
                clip_cov_lb: 1
                clip_cov_ratio: 0.0002
                clip_cov_ub: 5
                kl_cov_ratio: 0.0002
                loss_mode: vanilla
                ppo_kl_coef: 0.1
            ppo_epochs: 1
            ppo_max_token_len_per_gpu: 16384
            ppo_micro_batch_size: null
            ppo_micro_batch_size_per_gpu: 4
            ppo_mini_batch_size: 256
            profiler:
                _target_: verl.utils.profiler.ProfilerConfig
                all_ranks: false
                discrete: false
                ranks: []
            shuffle: false
            strategy: fsdp
            ulysses_sequence_parallel_size: 1
            use_dynamic_bsz: false
            use_kl_loss: true
            use_torch_compile: true
        hybrid_engine: true
        model:
            custom_chat_template: null
            enable_activation_offload: false
            enable_gradient_checkpointing: true
            exclude_modules: null
            external_lib: null
            fused_kernel_options:
                impl_backend: torch
            lora_alpha: 16
            lora_rank: 0
            path: Qwen/Qwen2.5-3B-Instruct
            target_modules: all-linear
            trust_remote_code: false
            use_fused_kernels: false
            use_liger: false
            use_remove_padding: true
            use_shm: false
        ref:
            entropy_checkpointing: false
            entropy_from_logits_with_chunking: false
            fsdp_config:
                forward_prefetch: false
                param_offload: true
                reshard_after_forward: true
                wrap_policy:
                    min_num_params: 0
            log_prob_max_token_len_per_gpu: 16384
            log_prob_micro_batch_size: null
            log_prob_micro_batch_size_per_gpu: 4
            log_prob_use_dynamic_bsz: false
            profiler:
                _target_: verl.utils.profiler.ProfilerConfig
                all_ranks: false
                discrete: false
                ranks: []
            strategy: fsdp
            ulysses_sequence_parallel_size: 1
            use_torch_compile: true
        rollout:
            agent:
                custom_async_server:
                    name: null
                    path: null
                num_workers: 8
            api_domain: rag_server
            calculate_log_probs: false
            disable_log_stats: true
            do_sample: true
            dtype: bfloat16
            enable_chunked_prefill: true
            enforce_eager: true
            engine_kwargs:
                sglang:
                    attention_backend: null
                vllm:
                    disable_mm_preprocessor_cache: false
                    swap_space: null
            free_cache_engine: true
            gpu_memory_utilization: 0.5
            ignore_eos: false
            layered_summon: false
            load_format: dummy_dtensor
            log_prob_max_token_len_per_gpu: 16384
            log_prob_micro_batch_size: null
            log_prob_micro_batch_size_per_gpu: 4
            log_prob_use_dynamic_bsz: false
            max_model_len: 32768
            max_num_batched_tokens: 8192
            max_num_seqs: 1024
            mode: sync
            multi_stage_wake_up: false
            multi_turn:
                completion_callback: null
                enable: true
                format: qwen
                interaction_config_path: config/interaction_config/autograph_interaction_config.yaml
                max_assistant_turns: 2
                max_parallel_calls: 1
                max_tool_response_length: 256
                max_user_turns: 2
                tokenization_sanity_check_mode: strict
                tool_config_path: null
                tool_response_truncate_side: middle
                use_inference_chat_template: false
            "n": 5
            name: sglang
            profiler:
                _target_: verl.utils.profiler.ProfilerConfig
                all_ranks: false
                discrete: false
                ranks: []
            prompt_length: 4096
            response_length: 4096
            temperature: 1
            tensor_model_parallel_size: 1
            top_k: -1
            top_p: 1
            use_api: true
            val_kwargs:
                do_sample: false
                "n": 1
                temperature: 0
                top_k: -1
                top_p: 1
algorithm:
    value:
        _target_: verl.trainer.config.AlgoConfig
        adv_estimator: grpo
        gamma: 1
        kl_ctrl:
            _target_: verl.trainer.config.KLControlConfig
            horizon: 10000
            kl_coef: 0.001
            target_kl: 0.1
            type: fixed
        kl_penalty: kl
        lam: 1
        norm_adv_by_std_in_grpo: true
        pf_ppo:
            _target_: verl.trainer.config.PFPPOConfig
            reweight_method: pow
            weight_pow: 2
        use_kl_in_reward: false
        use_pf_ppo: false
critic:
    value:
        checkpoint:
            load_contents:
                - model
                - optimizer
                - extra
            save_contents:
                - model
                - optimizer
                - extra
        cliprange_value: 0.5
        forward_max_token_len_per_gpu: 32768
        forward_micro_batch_size: null
        forward_micro_batch_size_per_gpu: null
        grad_clip: 1
        loss_agg_mode: token-mean
        model:
            enable_activation_offload: false
            enable_gradient_checkpointing: true
            external_lib: null
            fsdp_config:
                forward_prefetch: false
                fsdp_size: -1
                offload_policy: false
                optimizer_offload: false
                param_offload: false
                reshard_after_forward: true
                wrap_policy:
                    min_num_params: 0
            lora_alpha: 16
            lora_rank: 0
            path: ~/models/deepseek-llm-7b-chat
            target_modules: all-linear
            tokenizer_path: Qwen/Qwen2.5-3B-Instruct
            trust_remote_code: false
            use_remove_padding: false
            use_shm: false
        optim:
            lr: 1e-05
            lr_warmup_steps_ratio: 0
            min_lr_ratio: null
            total_training_steps: 500
            warmup_style: constant
            weight_decay: 0.01
        ppo_epochs: 1
        ppo_max_token_len_per_gpu: 32768
        ppo_micro_batch_size: null
        ppo_micro_batch_size_per_gpu: null
        ppo_mini_batch_size: 256
        profiler:
            _target_: verl.utils.profiler.ProfilerConfig
            all_ranks: false
            discrete: false
            ranks: []
        rollout_n: 5
        shuffle: false
        strategy: fsdp
        ulysses_sequence_parallel_size: 1
        use_dynamic_bsz: false
custom_reward_function:
    value:
        name: compute_score
        path: verl/third_party/autograph_r1/reward.py
data:
    value:
        custom_cls:
            name: null
            path: null
        dataloader_num_workers: 8
        filter_overlong_prompts: true
        filter_overlong_prompts_workers: 1
        image_key: images
        max_prompt_length: 4096
        max_response_length: 4096
        prompt_key: prompt
        return_full_prompt: false
        return_multi_modal_inputs: true
        return_raw_chat: true
        return_raw_input_ids: false
        reward_fn_key: data_source
        sampler:
            class_name: null
            class_path: null
        shuffle: false
        tokenizer: null
        train_batch_size: 512
        train_files: /home/httsangaj/projects/atlas-rl-dirs/autograph-r1/autograph-r1/data/musique_train_distract_False.parquet
        truncation: error
        trust_remote_code: false
        use_shm: false
        val_batch_size: 256
        val_files: /home/httsangaj/projects/atlas-rl-dirs/autograph-r1/autograph-r1/data/musique_validation_distract_False.parquet
        validation_shuffle: false
        video_key: videos
ray_init:
    value:
        num_cpus: null
        timeline_json_file: null
reward_model:
    value:
        enable: false
        forward_max_token_len_per_gpu: 32768
        launch_reward_fn_async: false
        max_length: null
        micro_batch_size: null
        micro_batch_size_per_gpu: null
        model:
            external_lib: null
            fsdp_config:
                forward_prefetch: false
                fsdp_size: -1
                param_offload: false
                reshard_after_forward: true
                wrap_policy:
                    min_num_params: 0
            input_tokenizer: Qwen/Qwen2.5-3B-Instruct
            path: ~/models/FsfairX-LLaMA3-RM-v0.1
            trust_remote_code: false
            use_fused_kernels: false
            use_remove_padding: false
            use_shm: false
        profiler:
            _target_: verl.utils.profiler.ProfilerConfig
            all_ranks: false
            discrete: false
            ranks: []
        reward_manager: naive
        sandbox_fusion:
            max_concurrent: 64
            memory_limit_mb: 1024
            url: null
        strategy: fsdp
        ulysses_sequence_parallel_size: 1
        use_dynamic_bsz: false
trainer:
    value:
        balance_batch: true
        controller_nsight_options:
            cuda-graph-trace: graph
            cuda-memory-usage: "true"
            trace: cuda,nvtx,cublas,ucx
        critic_warmup: 0
        default_hdfs_dir: null
        default_local_dir: /data/httsangaj/autograph/checkpoints/20250807_234936_qwen2.5-3B-autograph
        del_local_ckpt_after_load: false
        device: cuda
        esi_redundant_time: 0
        experiment_name: cpu7-qwen2.5-3B-auto-graph-rl
        log_val_generations: 0
        logger:
            - console
            - wandb
        max_actor_ckpt_to_keep: null
        max_critic_ckpt_to_keep: null
        n_gpus_per_node: 4
        nnodes: 1
        profile_steps: null
        project_name: auto_graph_rl
        ray_wait_register_center_timeout: 300
        resume_from_path: null
        resume_mode: auto
        rollout_data_dir: null
        save_freq: 100
        test_freq: 50
        total_epochs: 30
        total_training_steps: 500
        val_before_train: false
        val_only: false
        validation_data_dir: null
        worker_nsight_options:
            capture-range: cudaProfilerApi
            capture-range-end: null
            cuda-graph-trace: graph
            cuda-memory-usage: "true"
            kill: none
            trace: cuda,nvtx,cublas,ucx
