_wandb:
    value:
        cli_version: 0.21.0
        e:
            4pj490kiasyyjsic8b2vx5mc5746396f:
                args:
                    - --node-ip-address=10.22.4.100
                    - --node-manager-port=43759
                    - --object-store-name=/tmp/ray/session_2025-08-10_19-49-11_027217_661010/sockets/plasma_store
                    - --raylet-name=/tmp/ray/session_2025-08-10_19-49-11_027217_661010/sockets/raylet
                    - --redis-address=None
                    - --metrics-agent-port=44410
                    - --logging-rotate-bytes=536870912
                    - --logging-rotate-backup-count=5
                    - --runtime-env-agent-port=59773
                    - --gcs-address=10.22.4.100:63498
                    - --session-name=session_2025-08-10_19-49-11_027217_661010
                    - --temp-dir=/tmp/ray
                    - --webui=127.0.0.1:8265
                    - --cluster-id=c4a5daa854f123f10f185dfba2ef03a8ed873156deeaa05129add561
                    - --startup-token=224
                    - --worker-launch-time-ms=1754826563094
                    - --node-id=13e3143894b6d9260dd399a5f2598b35319845b8679f76bbea547a58
                    - --runtime-env-hash=-1624044036
                    - --enable-resource-isolation=false
                cpu_count: 112
                cpu_count_logical: 224
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "30601588170752"
                        used: "20688129912832"
                email: httsangaj@connect.ust.hk
                executable: /root/miniconda3/envs/verl/bin/python3
                git:
                    commit: ac431afc0286ec4346c3fb0449d4305e253f70bb
                    remote: git@github.com:gzone0111/autograph-r1.git
                gpu: NVIDIA H800
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H800
                      uuid: GPU-83dbe280-9177-5743-c89d-bb25d32c1692
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H800
                      uuid: GPU-53a12a61-670f-3ea2-c114-6101eb885bb6
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H800
                      uuid: GPU-6a789a18-9c99-60c7-4a55-ff0f1db0187e
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H800
                      uuid: GPU-2d6baed5-de0e-cb02-d5dc-03c7a20a74e0
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H800
                      uuid: GPU-dab0bbae-9115-b812-d645-aa3edfc96d91
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H800
                      uuid: GPU-d14bc897-fea2-4127-474a-fa95939a2bfe
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H800
                      uuid: GPU-a7b8c17d-3246-309b-3f68-cdaf0d6df72a
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H800
                      uuid: GPU-6a99c03d-a304-9574-849b-56c936e5aaf7
                host: dgx-26
                memory:
                    total: "2164195532800"
                os: Linux-5.15.0-1040-nvidia-x86_64-with-glibc2.35
                program: /root/miniconda3/envs/verl/lib/python3.10/site-packages/ray/_private/workers/default_worker.py
                python: CPython 3.10.18
                root: /workspace/autograph-r1
                slurm:
                    cluster_name: slurm
                    conf: /cm/shared/apps/slurm/var/etc/slurm/slurm.conf
                    cpus_on_node: "224"
                    distribution: cyclic
                    gpus_on_node: "8"
                    gpus_per_node: "8"
                    gtids: "0"
                    job_account: awskgraph
                    job_cpus_per_node: "224"
                    job_end_time: "1754999053"
                    job_gid: "3861"
                    job_gpus: 0,1,2,3,4,5,6,7
                    job_id: "253986"
                    job_name: auto_graph_training_7B
                    job_nodelist: dgx-26
                    job_num_nodes: "1"
                    job_partition: normal
                    job_qos: normal_qos
                    job_start_time: "1754826253"
                    job_uid: "3861"
                    job_user: httsangaj
                    jobid: "253986"
                    launch_node_ipaddr: 10.22.4.100
                    localid: "0"
                    mem_per_cpu: "8192"
                    mpi_type: pmix
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: dgx-26
                    nprocs: "1"
                    ntasks: "1"
                    ntasks_per_node: "1"
                    pmix_mapping_serv: (vector,(0,1,1))
                    pmixp_abort_agent_port: "41019"
                    prio_process: "0"
                    procid: "0"
                    srun_comm_host: 10.22.4.100
                    srun_comm_port: "42269"
                    step_gpus: 0,1,2,3,4,5,6,7
                    step_id: "0"
                    step_launcher_port: "42269"
                    step_nodelist: dgx-26
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /home/httsangaj/project/autograph-r1
                    submit_host: slogin-01
                    task_pid: "652201"
                    tasks_per_node: "1"
                    topology_addr: dgx-26
                    topology_addr_pattern: node
                    umask: "0007"
                    working_cluster: slurm:bcm2suheadnode-01:6817:9984:109
                startedAt: "2025-08-10T11:51:19.267356Z"
                writerId: 4pj490kiasyyjsic8b2vx5mc5746396f
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 50
                - 51
                - 71
                - 98
                - 105
            "2":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 50
                - 51
                - 71
                - 98
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.18
            "5": 0.21.0
            "6": 4.51.1
            "12": 0.21.0
            "13": linux-x86_64
actor_rollout_ref:
    value:
        actor:
            checkpoint:
                load_contents:
                    - model
                    - optimizer
                    - extra
                save_contents:
                    - model
                    - optimizer
                    - extra
            clip_ratio: 0.2
            clip_ratio_c: 3
            clip_ratio_high: 0.2
            clip_ratio_low: 0.2
            entropy_checkpointing: false
            entropy_coeff: 0
            entropy_from_logits_with_chunking: false
            fsdp_config:
                forward_prefetch: false
                fsdp_size: -1
                offload_policy: false
                optimizer_offload: false
                param_offload: false
                reshard_after_forward: true
                wrap_policy:
                    min_num_params: 0
            grad_clip: 1
            kl_loss_coef: 0.001
            kl_loss_type: low_var_kl
            loss_agg_mode: token-mean
            optim:
                lr: 1e-06
                lr_warmup_steps: -1
                lr_warmup_steps_ratio: 0.285
                min_lr_ratio: 0
                num_cycles: 0.5
                total_training_steps: 500
                warmup_style: constant
                weight_decay: 0.01
            policy_loss:
                clip_cov_lb: 1
                clip_cov_ratio: 0.0002
                clip_cov_ub: 5
                kl_cov_ratio: 0.0002
                loss_mode: vanilla
                ppo_kl_coef: 0.1
            ppo_epochs: 1
            ppo_max_token_len_per_gpu: 16384
            ppo_micro_batch_size: null
            ppo_micro_batch_size_per_gpu: 4
            ppo_mini_batch_size: 256
            profiler:
                _target_: verl.utils.profiler.ProfilerConfig
                all_ranks: false
                discrete: false
                ranks: []
            shuffle: false
            strategy: fsdp
            ulysses_sequence_parallel_size: 1
            use_dynamic_bsz: false
            use_kl_loss: true
            use_torch_compile: true
        hybrid_engine: true
        model:
            custom_chat_template: null
            enable_activation_offload: false
            enable_gradient_checkpointing: true
            exclude_modules: null
            external_lib: null
            fused_kernel_options:
                impl_backend: torch
            lora_alpha: 16
            lora_rank: 0
            path: Qwen/Qwen2.5-7B-Instruct
            target_modules: all-linear
            trust_remote_code: false
            use_fused_kernels: false
            use_liger: false
            use_remove_padding: true
            use_shm: false
        ref:
            entropy_checkpointing: false
            entropy_from_logits_with_chunking: false
            fsdp_config:
                forward_prefetch: false
                param_offload: true
                reshard_after_forward: true
                wrap_policy:
                    min_num_params: 0
            log_prob_max_token_len_per_gpu: 16384
            log_prob_micro_batch_size: null
            log_prob_micro_batch_size_per_gpu: 4
            log_prob_use_dynamic_bsz: false
            profiler:
                _target_: verl.utils.profiler.ProfilerConfig
                all_ranks: false
                discrete: false
                ranks: []
            strategy: fsdp
            ulysses_sequence_parallel_size: 1
            use_torch_compile: true
        rollout:
            agent:
                custom_async_server:
                    name: null
                    path: null
                num_workers: 8
            api_domain: rag_server
            calculate_log_probs: false
            disable_log_stats: true
            do_sample: true
            dtype: bfloat16
            enable_chunked_prefill: true
            enforce_eager: true
            engine_kwargs:
                sglang:
                    attention_backend: null
                vllm:
                    disable_mm_preprocessor_cache: false
                    swap_space: null
            free_cache_engine: true
            gpu_memory_utilization: 0.7
            ignore_eos: false
            layered_summon: false
            load_format: dummy_dtensor
            log_prob_max_token_len_per_gpu: 16384
            log_prob_micro_batch_size: null
            log_prob_micro_batch_size_per_gpu: 4
            log_prob_use_dynamic_bsz: false
            max_model_len: 32768
            max_num_batched_tokens: 8192
            max_num_seqs: 1024
            mode: sync
            multi_stage_wake_up: false
            multi_turn:
                completion_callback: null
                enable: true
                format: qwen
                interaction_config_path: config/interaction_config/autograph_interaction_config.yaml
                max_assistant_turns: 2
                max_parallel_calls: 1
                max_tool_response_length: 256
                max_user_turns: 2
                tokenization_sanity_check_mode: strict
                tool_config_path: null
                tool_response_truncate_side: middle
                use_inference_chat_template: false
            "n": 5
            name: sglang
            profiler:
                _target_: verl.utils.profiler.ProfilerConfig
                all_ranks: false
                discrete: false
                ranks: []
            prompt_length: 8192
            response_length: 8192
            temperature: 1
            tensor_model_parallel_size: 1
            top_k: -1
            top_p: 1
            use_api: true
            val_kwargs:
                do_sample: false
                "n": 1
                temperature: 0
                top_k: -1
                top_p: 1
algorithm:
    value:
        _target_: verl.trainer.config.AlgoConfig
        adv_estimator: grpo
        gamma: 1
        kl_ctrl:
            _target_: verl.trainer.config.KLControlConfig
            horizon: 10000
            kl_coef: 0.001
            target_kl: 0.1
            type: fixed
        kl_penalty: kl
        lam: 1
        norm_adv_by_std_in_grpo: true
        pf_ppo:
            _target_: verl.trainer.config.PFPPOConfig
            reweight_method: pow
            weight_pow: 2
        use_kl_in_reward: false
        use_pf_ppo: false
critic:
    value:
        checkpoint:
            load_contents:
                - model
                - optimizer
                - extra
            save_contents:
                - model
                - optimizer
                - extra
        cliprange_value: 0.5
        forward_max_token_len_per_gpu: 32768
        forward_micro_batch_size: null
        forward_micro_batch_size_per_gpu: null
        grad_clip: 1
        loss_agg_mode: token-mean
        model:
            enable_activation_offload: false
            enable_gradient_checkpointing: true
            external_lib: null
            fsdp_config:
                forward_prefetch: false
                fsdp_size: -1
                offload_policy: false
                optimizer_offload: false
                param_offload: false
                reshard_after_forward: true
                wrap_policy:
                    min_num_params: 0
            lora_alpha: 16
            lora_rank: 0
            path: ~/models/deepseek-llm-7b-chat
            target_modules: all-linear
            tokenizer_path: Qwen/Qwen2.5-7B-Instruct
            trust_remote_code: false
            use_remove_padding: false
            use_shm: false
        optim:
            lr: 1e-05
            lr_warmup_steps_ratio: 0
            min_lr_ratio: null
            total_training_steps: 500
            warmup_style: constant
            weight_decay: 0.01
        ppo_epochs: 1
        ppo_max_token_len_per_gpu: 32768
        ppo_micro_batch_size: null
        ppo_micro_batch_size_per_gpu: null
        ppo_mini_batch_size: 256
        profiler:
            _target_: verl.utils.profiler.ProfilerConfig
            all_ranks: false
            discrete: false
            ranks: []
        rollout_n: 5
        shuffle: false
        strategy: fsdp
        ulysses_sequence_parallel_size: 1
        use_dynamic_bsz: false
custom_reward_function:
    value:
        name: compute_score
        path: verl/third_party/autograph_r1/reward.py
data:
    value:
        custom_cls:
            name: null
            path: null
        dataloader_num_workers: 8
        filter_overlong_prompts: true
        filter_overlong_prompts_workers: 1
        image_key: images
        max_prompt_length: 8192
        max_response_length: 8192
        prompt_key: prompt
        return_full_prompt: false
        return_multi_modal_inputs: true
        return_raw_chat: true
        return_raw_input_ids: false
        reward_fn_key: data_source
        sampler:
            class_name: null
            class_path: null
        shuffle: false
        tokenizer: null
        train_batch_size: 512
        train_files: /workspace/autograph-r1/autograph-r1/data/musique_train_distract_False.parquet
        truncation: error
        trust_remote_code: false
        use_shm: false
        val_batch_size: 256
        val_files: /workspace/autograph-r1/autograph-r1/data/musique_validation_distract_False.parquet
        validation_shuffle: false
        video_key: videos
ray_init:
    value:
        num_cpus: null
        timeline_json_file: null
reward_model:
    value:
        enable: false
        forward_max_token_len_per_gpu: 32768
        launch_reward_fn_async: false
        max_length: null
        micro_batch_size: null
        micro_batch_size_per_gpu: null
        model:
            external_lib: null
            fsdp_config:
                forward_prefetch: false
                fsdp_size: -1
                param_offload: false
                reshard_after_forward: true
                wrap_policy:
                    min_num_params: 0
            input_tokenizer: Qwen/Qwen2.5-7B-Instruct
            path: ~/models/FsfairX-LLaMA3-RM-v0.1
            trust_remote_code: false
            use_fused_kernels: false
            use_remove_padding: false
            use_shm: false
        profiler:
            _target_: verl.utils.profiler.ProfilerConfig
            all_ranks: false
            discrete: false
            ranks: []
        reward_manager: naive
        sandbox_fusion:
            max_concurrent: 64
            memory_limit_mb: 1024
            url: null
        strategy: fsdp
        ulysses_sequence_parallel_size: 1
        use_dynamic_bsz: false
trainer:
    value:
        balance_batch: true
        controller_nsight_options:
            cuda-graph-trace: graph
            cuda-memory-usage: "true"
            trace: cuda,nvtx,cublas,ucx
        critic_warmup: 0
        default_hdfs_dir: null
        default_local_dir: /project/awskgraph/autograph/checkpoints/20250810_194907_qwen2.5-7b-autograph
        del_local_ckpt_after_load: false
        device: cuda
        esi_redundant_time: 0
        experiment_name: superpod-qwen2.5-7b-auto-graph-rl
        log_val_generations: 0
        logger:
            - console
            - wandb
        max_actor_ckpt_to_keep: null
        max_critic_ckpt_to_keep: null
        n_gpus_per_node: 4
        nnodes: 1
        profile_steps: null
        project_name: auto_graph_rl
        ray_wait_register_center_timeout: 300
        resume_from_path: null
        resume_mode: auto
        rollout_data_dir: null
        save_freq: 100
        test_freq: 50
        total_epochs: 30
        total_training_steps: 500
        val_before_train: false
        val_only: false
        validation_data_dir: null
        worker_nsight_options:
            capture-range: cudaProfilerApi
            capture-range-end: null
            cuda-graph-trace: graph
            cuda-memory-usage: "true"
            kill: none
            trace: cuda,nvtx,cublas,ucx
